### GET request to example server
GET {{server}}
#Authorization: Bearer {{$auth.token("keycloak")}}

### GET all Baked in Services
GET {{server}}/baked
#Authorization: Bearer {{$auth.token("keycloak")}}
Accept: application/json